### ISSUE TITLE
Add possibility to specify scale

### ISSUE THREAD

**Issue by kkizlaitis** [aliyigitbireroglu/flutter-spring-button#2]
Right now, a SpringButton will scale to a predefined value when being pressed on. It would be great if we could specify a scale of our own.

**Comment by aliyigitbireroglu** [comment]
The new update introduces

`scaleCoefficient`

and as explained: Use this value to determine the scaling factor while the animation is being played. Choose a value between 0.0 and 1.0.

**Comment by kkizlaitis** [comment]
You are absolutely right. I don't know how I missed that.

This issue can now be closed :)

EDIT:
Oh it's because it was added only now 😄 Thank you for being so quick!

**Comment by aliyigitbireroglu** [comment]
Yes exactly 😃 No problem, happy coding!
