### ISSUE TITLE
Can't handle onTap event when user tap on title of button

### ISSUE THREAD

**Issue by nttra83** [aliyigitbireroglu/flutter-spring-button#3]
Hello,
Can't handle the onTap event when the user tap on the title of a button.

How we can handle it?

I created a Login button with code below:
<img width="382" alt="Screen Shot 2020-01-13 at 01 22 33" src="https://user-images.githubusercontent.com/24289191/72223606-50d06f00-35a3-11ea-9771-45a5a70ca520.png">

**Comment by aliyigitbireroglu** [comment]
Hi,

Having ran the code myself, I can confirm that it is handling the onTap event as it should. What is the problem you are getting?

**Comment by nttra83** [comment]
Hi aliyigitbireroglu,
I fixed this issue on my side. 
The reason: I'm using flutter_progress_hud for show HUD, I removed it then login button work perfect :).
Thank you aliyigitbireroglu
