### ISSUE TITLE
Can't change the Spring button color

### ISSUE THREAD

**Issue by mohantyagii** [aliyigitbireroglu/flutter-spring-button#5]
Can't change the Spring button color dynamically,
if i have some color intiallly and want to change later with setState, it doesn't reflect to the button child: SpringButton(
  
  Source Code:
  
      SpringButton(  
        SpringButtonType.OnlyScale,
        Container(
          height: ScreenUtil.getInstance().setHeight(50),
          width: MediaQuery.of(context).size.width * 0.78,
          decoration:BoxDecoration(
            shape: BoxShape.rectangle,
            color: dynamicButtonColor,
            borderRadius: BorderRadius.circular(5.0),
          ) ,
          child: Center(
            child: Text(
             "ABC",
              style: GoogleFonts.openSans(
                fontWeight: FontWeight.w600,
                fontSize: ScreenUtil(allowFontScaling: true).setSp(14),
                color: AppColors.whiteText,
              ),
              textScaleFactor: 1.0,
            ),
          ),
        ),
        onTapDown: (_) => {
      
    
        },
      )
)

**Comment by aliyigitbireroglu** [comment]
Hello,

Can you also try with "useCache" set to false? And if that doesn't work, please try assigning a "Key" value to the widget and updating this value when you want to change the colour.

**Comment by mohantyagii** [comment]
key: ObjectKey(yourDynamicColor),
 
 This works for me
 
 Thanks for the update
