### ISSUE TITLE
NULL SAFETY

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [aliyigitbireroglu/flutter-spring-button#7]
Hello
Any plans to migrate to null safety?

**Comment by aliyigitbireroglu** [comment]
Yes, as soon as I have time I will do so. Probably next week.

**Comment by MojtabaTavakkoli** [comment]
Greate! Take your time.

**Comment by aliyigitbireroglu** [comment]
The package was updated to support null safety. Enjoy!
